# Action Framework Load Function
# Generated by RunToolkit Framework Builder v2.0.0
# https://github.com/runtoolkit
# Build Date: 2026-04-29 18:28:07

# ============================================
# SCOREBOARD INITIALIZATION
# ============================================

scoreboard objectives add af.system dummy "AF System"
scoreboard objectives add af.action dummy "AF Action"
scoreboard objectives add af.chain dummy "AF Chain"
scoreboard objectives add af.timer dummy "AF Timer"
scoreboard objectives add af.player dummy "AF Player"
scoreboard objectives add af.temp dummy "AF Temp"
scoreboard objectives add af.config dummy "AF Config"
scoreboard objectives add af.trigger trigger "AF Trigger"
scoreboard objectives add af.event dummy "AF Event"

# Health tracking (optional)
scoreboard objectives add af.health health {"text":"❤","color":"red"}
scoreboard objectives add af.death deathCount "Deaths"

# ============================================
# STORAGE INITIALIZATION
# ============================================

# Main storage
data merge storage action_framework:main {\
    initialized:1b,\
    version:"2.0.0",\
    mc_version:"1.21.4",\
    build_date:"{datetime.now().isoformat()}",\
    config:{\
        debug:0b,\
        log_actions:1b,\
        max_queue_size:100,\
        tick_rate:20\
    }\
}

# Action storage
data merge storage action_framework:actions {\
    queue:[],\
    active:[],\
    completed:[],\
    failed:[]\
}

# Macro storage
data merge storage action_framework:macros {\
    templates:{},\
    cache:{}\
}

# Temporary storage
data merge storage action_framework:temp {\
    data:{},\
    current_action:{},\
    chain_actions:[]\
}

# Event storage
data merge storage action_framework:events {\
    listeners:{},\
    queue:[]\
}

# Player data storage
data merge storage action_framework:players {\
    data:{},\
    online:[]\
}

# ============================================
# SYSTEM CONSTANTS
# ============================================

scoreboard players set #-1 af.system -1
scoreboard players set #0 af.system 0
scoreboard players set #1 af.system 1
scoreboard players set #2 af.system 2
scoreboard players set #5 af.system 5
scoreboard players set #10 af.system 10
scoreboard players set #20 af.system 20
scoreboard players set #50 af.system 50
scoreboard players set #100 af.system 100
scoreboard players set #1000 af.system 1000

# Version number
scoreboard players set #major af.system 2
scoreboard players set #minor af.system 0
scoreboard players set #patch af.system 0

# ============================================
# TEAM SETUP (for visual effects)
# ============================================

team add af.admin "AF Admin"
team modify af.admin color gold
team modify af.admin prefix {"text":"[AF] ","color":"gold","bold":true}

team add af.debug "AF Debug"
team modify af.debug color yellow
team modify af.debug prefix {"text":"[DEBUG] ","color":"yellow"}

# ============================================
# GAMERULES (optional, configurable)
# ============================================

# Uncomment if needed:
# gamerule commandBlockOutput false
# gamerule sendCommandFeedback false
# gamerule logAdminCommands false

# ============================================
# LOAD MESSAGE
# ============================================

tellraw @a ["",\
    {"text":"\n================================\n","color":"dark_gray"},\
    {"text":"  Action Framework  ","color":"gold","bold":true},\
    {"text":"\n"},\
    {"text":"  Version: ","color":"gray"},\
    {"text":"2.0.0","color":"yellow"},\
    {"text":"\n"},\
    {"text":"  Minecraft: ","color":"gray"},\
    {"text":"1.21.4","color":"aqua"},\
    {"text":"\n"},\
    {"text":"  Status: ","color":"gray"},\
    {"text":"✓ Loaded","color":"green","bold":true},\
    {"text":"\n"},\
    {"text":"  [Docs]","color":"aqua","underlined":true,\
        "clickEvent":{"action":"open_url","value":"https://github.com/runtoolkit"},\
        "hoverEvent":{"action":"show_text","contents":"Dokümantasyonu aç"}},\
    {"text":" | "},\
    {"text":"[GitHub]","color":"white","underlined":true,\
        "clickEvent":{"action":"open_url","value":"https://github.com/runtoolkit"},\
        "hoverEvent":{"action":"show_text","contents":"GitHub'da görüntüle"}},\
    {"text":"\n================================\n","color":"dark_gray"}\
]

# Play load sound
execute as @a at @s run playsound minecraft:block.note_block.pling master @s ~ ~ ~ 0.5 2

# ============================================
# INITIALIZE SUBSYSTEMS
# ============================================

function action_framework:internal/init
function action_framework:systems/event_init
function action_framework:systems/player_init

# ============================================
# SETUP COMPLETE
# ============================================

scoreboard players set #initialized af.system 1
data modify storage action_framework:main system_ready set value 1b

# Debug log
execute if data storage action_framework:main {config:{debug:1b}} run tellraw @a[tag=af.debug] [\
    {"text":"[AF Debug] ","color":"yellow"},\
    {"text":"Framework initialized successfully","color":"green"}\
]
